### ISSUE TITLE
Consider switching the promises implementation to Bluebird?

### ISSUE THREAD

**Issue by pesho** [OptimalBits/fowl#3]
[Bluebird](https://github.com/petkaantonov/bluebird) is [much faster](https://github.com/petkaantonov/bluebird/blob/master/benchmark/stats/latest.md) than When, without sacrificing features.

**Comment by manast** [comment]
I know about bluebird, but I am not sure there is a bottleneck on the promise part of fowl. Before changing to bluebird I would like to be sure that there is some performance gain at all.

**Comment by manast** [comment]
I ended upgrading because bluebird has so much better error and exception handling.

**Comment by pesho** [comment]
Thanks. You are right that the performance gain is difficult to determine without benchmarking.
