### ISSUE TITLE
Tests fail on 2.0.5

### ISSUE THREAD

**Issue by koresar** [OptimalBits/fowl#5]
The following tests fail on FoundationDB 2.0.5
(ubuntu 12.04 x64)

```
      Condition Operators
        1) equality operator
        2) equality operator using index
        3) Greater than
        4) Greater or Equal than
```

The native 'commit' function returns success but no data (undefined). See screenshot: http://screencloud.net/v/FcpK

**Comment by manast** [comment]
Since Foundation 2.0.x I have not been able to make the unit tests to work. I have spent some time debugging without understanding what is wrong... very few people is showing interest in this library at the moment so I have not prioritised to fix the issues...

**Comment by koresar** [comment]
I could try to supply a pull request to make it work with 2.0. Although I am not able to test on earlier versions. What do you think?

**Comment by manast** [comment]
If it works on 2.0 it is ok. I don't think there is anybody using it in production anyways. :)

**Comment by koresar** [comment]
Perfect! Give me some time.

**Comment by manast** [comment]
Btw, if you are interested in developing this library further, you can check this https://www.npmjs.org/package/sift to get a more complete mongodb query support...

**Comment by koresar** [comment]
Seems like my fdb knowledge is too weak to fix the issue. It's easier to create own layer than fix this one. Sorry, Manuel.

**Comment by manast** [comment]
@koresar I fixed the issues. At least on my setup all unit tests and some others are working now with fdb 2.0

**Comment by koresar** [comment]
Muchas gracias!
