### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by djMax** [OptimalBits/fowl#8]
FDB is on 3.x now, wondering if you plan on updating and extending this module or if it makes more sense to go direct against fdb.

**Comment by koresar** [comment]
I believe `fowl` should work with FDB 3.0 without any changes.

AFAIK the owner does not plan to extend the module unless someone submit PR(s).

**Comment by manast** [comment]
There are things going on at foundationdb that makes this module obsolete...

**Comment by koresar** [comment]
Yeah. I tried those "things". It's awesome and groundbreaking (for me). :)
Cheers
